diff_drive:
  ros__parameters:
    base_link_mass: 1.14395
    base_link_inertia: 
      ixx: 0.126164
      ixy: 0.0
      ixz: 0.0
      iyy: 0.416519
      iyz: 0.0
      izz: 0.481014
    base_link_dimensions:
      length: 2.01142
      width: 1.0
      height: 0.568726

    wheel_radius: 0.3
    wheel_mass: 2.0
    wheel_inertia:
      ixx: 0.145833
      ixy: 0.0
      ixz: 0.0
      iyy: 0.145833
      iyz: 0.0
      izz: 0.125
      
    caster_mass: 1.0
    caster_radius: 0.2
    caster_inertia:
      ixx: 0.1
      ixy: 0.0
      ixz: 0.0
      iyy: 0.1
      iyz: 0.0
      izz: 0.1
