/**:
  ros__parameters:
    robot_dimensions:
      body_length: 1.0  # Length (a)
      body_height: 0.3  # Height (b)
      body_width: 0.6   # Width (c)

    wheel_dimensions:
      wheel_radius: 0.3
      wheel_thickness: 0.1  # Thickness (d)

    caster_dimensions:
      caster_radius: 0.1

    masses:
      body_mass: 1.0
      wheel_mass: 10.0
      caster_mass: 1.0
